import Photos

extension PHAssetResource {
    /// Resolves "FullSizeRender" filenames (generated by iOS for edited photos)
    /// back to the original photo resource's filename.
    func resolvedFilename() -> String {
        let filename = originalFilename
        let nameWithoutExtension = (filename as NSString).deletingPathExtension

        guard nameWithoutExtension == "FullSizeRender" else {
            return filename
        }

        let assets = PHAsset.fetchAssets(
            withLocalIdentifiers: [assetLocalIdentifier],
            options: nil
        )
        guard let asset = assets.firstObject else {
            return filename
        }

        return Self.resolveEditedFilename(filename, asset: asset)
    }

    /// Resolves "FullSizeRender" filenames using an already-fetched PHAsset,
    /// avoiding a redundant fetch when the asset is already available.
    func resolvedFilename(using asset: PHAsset) -> String {
        let filename = originalFilename
        let nameWithoutExtension = (filename as NSString).deletingPathExtension

        guard nameWithoutExtension == "FullSizeRender" else {
            return filename
        }

        return Self.resolveEditedFilename(filename, asset: asset)
    }

    private static func resolveEditedFilename(
        _ filename: String, asset: PHAsset
    ) -> String {
        let resources = PHAssetResource.assetResources(for: asset)
        guard let originalResource = resources.first(where: {
            ($0.type == .photo || $0.type == .fullSizePhoto)
                && !$0.originalFilename.hasPrefix("FullSizeRender")
        }) else {
            return filename
        }

        let originalName =
            (originalResource.originalFilename as NSString).deletingPathExtension
        let editedExtension = (filename as NSString).pathExtension

        if editedExtension.isEmpty {
            return originalResource.originalFilename
        }
        return "\(originalName).\(editedExtension)"
    }
}
