import Photos

extension PHAssetResource {
    /// Resolves "FullSizeRender" filenames (generated by iOS for edited photos)
    /// back to the original photo resource's filename.
    func resolvedFilename() -> String {
        let filename = originalFilename
        let nameWithoutExtension = (filename as NSString).deletingPathExtension

        guard nameWithoutExtension == "FullSizeRender" else {
            return filename
        }

        let assets = PHAsset.fetchAssets(
            withLocalIdentifiers: [assetLocalIdentifier],
            options: nil
        )
        guard let asset = assets.firstObject else {
            return filename
        }

        return Self.resolveEditedFilename(filename, asset: asset)
    }

    /// Resolves "FullSizeRender" filenames using an already-fetched PHAsset,
    /// avoiding a redundant fetch when the asset is already available.
    func resolvedFilename(using asset: PHAsset) -> String {
        let filename = originalFilename
        let nameWithoutExtension = (filename as NSString).deletingPathExtension

        guard nameWithoutExtension == "FullSizeRender" else {
            return filename
        }

        return Self.resolveEditedFilename(filename, asset: asset)
    }

    private static func resolveEditedFilename(
        _ filename: String, asset: PHAsset
    ) -> String {
        let resources = PHAssetResource.assetResources(for: asset)
        let editedExtension = (filename as NSString).pathExtension

        // Try photo companion resource first (edited stills, Live Photos)
        if let photoResource = resources.first(where: {
            ($0.type == .photo || $0.type == .fullSizePhoto)
                && !$0.originalFilename.hasPrefix("FullSizeRender")
        }) {
            let originalName =
                (photoResource.originalFilename as NSString).deletingPathExtension
            if editedExtension.isEmpty {
                return photoResource.originalFilename
            }
            return "\(originalName).\(editedExtension)"
        }

        // For pure video assets (e.g. Apple Log HDR exported by third-party camera apps),
        // fall back to the .video resource to recover the captured filename.
        if let videoResource = resources.first(where: {
            $0.type == .video
                && !$0.originalFilename.hasPrefix("FullSizeRender")
        }) {
            let originalName =
                (videoResource.originalFilename as NSString).deletingPathExtension
            if editedExtension.isEmpty {
                return videoResource.originalFilename
            }
            return "\(originalName).\(editedExtension)"
        }

        return filename
    }
}
