#!/bin/bash

# Build script to generate version information including Git SHA
# This script runs as a build phase in Xcode to automatically populate BuildInfo.swift

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}/.."
OUTPUT_FILE="${PROJECT_DIR}/YAIIU/Generated/BuildInfo.swift"

# Ensure the output directory exists
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# Get version from build settings (MARKETING_VERSION)
VERSION="${MARKETING_VERSION:-0.0.0}"

# Get build number from build settings (CURRENT_PROJECT_VERSION)
BUILD_NUMBER="${CURRENT_PROJECT_VERSION:-1}"

# Get Git SHA (short form)
if git rev-parse --git-dir > /dev/null 2>&1; then
    GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_SHA_FULL=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
    
    # Check for uncommitted changes
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
        GIT_SHA="${GIT_SHA}-dirty"
    fi
else
    GIT_SHA="unknown"
    GIT_SHA_FULL="unknown"
fi

# Get build date in ISO 8601 format
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate the Swift file
cat > "${OUTPUT_FILE}" << EOF
// Auto-generated file. Do not edit manually.
// Generated by set_build_info.sh

import Foundation

enum BuildInfo {
    static let version = "${VERSION}"
    static let buildNumber = "${BUILD_NUMBER}"
    static let gitSHA = "${GIT_SHA}"
    static let gitSHAFull = "${GIT_SHA_FULL}"
    static let buildDate = "${BUILD_DATE}"
    
    static var versionString: String {
        "\(version) (\(buildNumber))"
    }
    
    static var fullVersionString: String {
        "\(version) (\(buildNumber)) [\(gitSHA)]"
    }
}
EOF

echo "Generated BuildInfo.swift with version ${VERSION} (${BUILD_NUMBER}) [${GIT_SHA}]"
